name: Pull Request

on:
  pull_request:
    branches: [ "main", "v1-php8" ]

jobs:
  test_pull_request:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: intl, bcmath

      - name: Composer Install
        run: composer install

      - name: Check Style
        run: make style

      - name: Analyze code
        run: make analyze

      - name: Run tests
        run: make check-coverage
