name: Test Main Branch

on:
  push:
    branches: [ "main" ]

jobs:
  test-main:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Composer Install
        uses: php-actions/composer@v6
        with:
          php_version: 8.2
          php_extensions: intl bcmath

      - name: Check Style
        run: make style

      - name: Analyze code
        run: make analyze

      - name: Run tests
        run: make coveralls
